version: '3.8'

services:
  postgres:
    image: postgres:11.5
    restart: always
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=ems_db
    ports: 
      - 5432:5432
    volumes:
      - ${HOME}/docker-postgres-data/:/var/lib/postgresql/data
      - ./database/ems-db.sql:/docker-entrypoint-initdb.d/ems-db.sql
  auth-server:
    build: ./backend/auth-server/
    image: auth-server-ems
    restart: unless-stopped
    ports: 
      - 3000:3000
    environment:
      - AUTH_PORT=${AUTH_PORT}
      - ACCESS_SALT=${ACCESS_SALT}
      - REFRESH_SALT=${REFRESH_SALT}
    depends_on:
      - postgres
  api-server:
    build: ./backend/api-server/
    image: api-server-ems
    restart: unless-stopped
    ports: 
      - 3001:3001
    environment:
      - API_PORT=${API_PORT}
      - ACCESS_SALT=${ACCESS_SALT}
    depends_on:
      - postgres
      - auth-server